server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://25.20.56.232:3306/patakparlat
    username: root
    password: macilaci2024
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
logging:
  level:
    org.springframework.web.servlet.handler.AbstractHandlerMapping: DEBUG
