
spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:52390/railway
    username: root
    password: -3eGG3g422cGe565f6e4252DDdD4ae43
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
