
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bgbktjelvvok3rzysddo?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQLDialect


logging:
  level:
    root: INFO
    hu.balogh.dummyapi: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
