
spring:
  datasource:
    url: jdbc:mysql://roundhouse.proxy.rlwy.net:52390/railway
    username: root
    password: -3eGG3g422cGe565f6e4252DDdD4ae43
    hikari:
      max-lifetime: 0
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true



logging:
  level:
    root: null
    hu.balogh.dummyapi: DEBUG
    org:
      hibernate: debug
    sql: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
