
spring:
  datasource:
    url: jdbc:mysql://bgbktjelvvok3rzysddo-mysql.services.clever-cloud.com/bgbktjelvvok3rzysddo?createDatabaseIfNotExist=true
    username: ul9bbptz5su7bthc
    password: rHghJl337MVcLCvizPnO
  jpa:
    hibernate:
      ddl-auto: update


logging:
  level:
    root: INFO
    hu.balogh.dummyapi: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
