
spring:
  datasource:
    url: jdbc:mysql://sql11.freesqldatabase.com:3306/sql11672071?createDatabaseIfNotExist=true
    username: sql11672071
    password: dq7ZEKhYV3
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false


logging:
  level:
    root: INFO
    hu.balogh.dummyapi: DEBUG
    org:
      hibernate: debug

springdoc:
  swagger-ui:
    path: /swagger-ui.html
