
spring:
  data:
    mongodb:
      uri: "mongodb+srv://kosuthvt:i79FwnoIqdROzLtS@southvt-be.873qgat.mongodb.net/southvt-be?tls=true&ssl=true&readPreference=secondary"


logging:
  level:
    root: INFO
    hu.balogh.dummyapi: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
