server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://91.229.245.186:3306/patakparlat
    username: root
    password: Gennyesfityma42
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
    show-sql: true
logging:
  level:
    org.springframework.web.servlet.handler.AbstractHandlerMapping: DEBUG
